# Generated by Django 4.1.2 on 2022-12-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionApp', '0003_remove_bid_item_item_cur_bid_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='winner_informed',
            field=models.BooleanField(default=False),
        ),
    ]
